
stages:
  - test

unittests_py3:
  image: danbla/fuglupy3
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - fuglu --lint
    - nosetests-3.4 --rednose testing
  except:
    - develop

unittests_py2:
  image: danbla/fuglupy2
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - fuglu --lint
    - nosetests --rednose testing
  except:
    - develop

# special image for develop branch
unittests_dev_py3:
  image: danbla/fuglupy3:develop
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - fuglu --lint
    - nosetests-3.4 --rednose testing
  only:
    - develop

unittests_dev_py2:
  image: danbla/fuglupy2:develop
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - fuglu --lint
    - nosetests --rednose testing
  only:
    - develop

